### ISSUE TITLE
Интерфейсы и их реализации

### ISSUE THREAD

**Issue by motskin** [plusbear/BookReselling#6]
Например Services -> Catalog -> Services -> Repository
Вот как можно навести порядок, чтобы интерфейсы и их реализации не перемешивались?
![image](https://user-images.githubusercontent.com/23341974/124719114-78419700-df0f-11eb-9a21-b3e0d574bbe1.png)

**Comment by plusbear** [comment]
Отдельная папка для интерфейсов?
